name: Checks

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

env:
  # We pin the exact version to enforce reproducable builds with node + npm.
  DEFAULT_NODE_VERSION: "16.15.1"

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn build

  type-check:
    needs: build
    name: Typing check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn check:types

  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn check:formatting

  test-unit:
    needs: build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn test:unit

  test-integration:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn test:integration

  test-e2e:
    needs: build
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.E2E_TESTS_SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn test:e2e

  lint:
    needs: build
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn lint

  artifacts:
    needs: build
    name: Upload Artifacts
    runs-on: ubuntu-latest
    # Build artifacts are only needed for releasing workflow.
    # TODO comment back in
    # if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      # - name: Check dependency cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.CACHED_DEPENDENCY_PATHS }}
      #     key: ${{ needs.job_build.outputs.dependency_cache_key }}
      # - name: Check build cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.CACHED_BUILD_PATHS }}
      #     key: ${{ env.BUILD_CACHE_KEY }}
      - run: yarn --frozen-lockfile
      - name: pack
        run: yarn build:npm
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/packages/*/dist/**
            ${{ github.workspace }}/packages/**/*.tgz
