name: Checks

on:
  push:
    branches: [main]
  pull_request:

env:
  DEFAULT_NODE_VERSION: "16.15.1"

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn build

  type-check:
    name: Typing check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn check:types

  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn check:formatting

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: yarn --frozen-lockfile
      - run: yarn check:formatting
